[package]
name = "temperature-converter-rs"
version = "0.1.0"
authors = ["Darren Christopher <a@atsui.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
